name: odin
channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/numba # numba
  - defaults
dependencies:
  - python=3.5

  # scientific computing
  - numpy=1.15.2
  - scipy=1.1.0
  - numba=0.39.0
  - scikit-learn=0.20.0

  # visualization interactive ipython and notebook
  - matplotlib=3.0.0

  # data processing and management
  - pandas=0.23.4
  - dill # for pickling functions and iteration

  # others
  - nose
  - six
  - colorama

  # networking
  - pycrypto

  # signal processing
  - resampy

  # python docs
  - Sphinx

  - pip:
    - soundfile # read sph audio file python
    - tensorflow-gpu
    - tensorflow-probability
    - tqdm
    - daft

