name: odin
channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/numba # numba
  - defaults
dependencies:
  - python=3.5

  # scienctific computing
  - numpy=1.15.2
  - scipy=1.1.0
  - numba=0.39.0
  - scikit-learn=0.19.2

  # visualization interactive ipython and notebook
  - matplotlib

  # data processing and management
  - pandas
  - dill # for pickling functions and iteration

  # others
  - nose
  - six
  - colorama

  # networking
  - pycrypto
  - requests

  # signal processing
  - resampy

  # python docs
  - Sphinx

  - pip:
    - soundfile # read sph audio file python
    - tensorflow-gpu
    - tqdm
