name: ai
channels:
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip>=19.0
  - numpy>=1.9.1
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - tensorflow-gpu==1.13.1
    - tensorflow-probability==0.6.0
    - tensorflow-datasets
    - six>=1.9.0
    - scikit-learn>=0.20.0
    - matplotlib>=3.0.0
    - decorator
    - tqdm
    - dill
    - pycrypto
    - colorama
    - pydot>=1.2.4
    - seaborn
    - pytest
    - pandas
    - requests
    - soundfile
    - resampy